// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The definition of Block
type Block struct {
	// Header of Block
	Header *BlockHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	// Transactions of Block
	Transactions         []*Tx    `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_ccd341c96022d260, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Tx {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// The definition of BlockHeader
type BlockHeader struct {
	Version   int32  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	ChannelID string `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Number    uint64 `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	// The hash of PrevBlock
	PrevBlock []byte `protobuf:"bytes,4,opt,name=PrevBlock,proto3" json:"PrevBlock,omitempty"`
	// Do this should change to BitCoin as MerkleRoot?
	MerkleRoot           []byte   `protobuf:"bytes,5,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_ccd341c96022d260, []int{1}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetPrevBlock() []byte {
	if m != nil {
		return m.PrevBlock
	}
	return nil
}

func (m *BlockHeader) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*BlockHeader)(nil), "protos.BlockHeader")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_block_ccd341c96022d260) }

var fileDescriptor_block_ccd341c96022d260 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0xbb, 0xbb, 0xda, 0xd9, 0x9e, 0x46, 0x90, 0x41, 0x44, 0x42, 0x4f, 0x01, 0x61,
	0x0f, 0xf5, 0x0d, 0xd4, 0x83, 0x1e, 0x14, 0x09, 0x8b, 0xf7, 0x6c, 0x3b, 0xe0, 0xd2, 0x6d, 0x22,
	0x49, 0x94, 0xbe, 0x95, 0xaf, 0x28, 0x4d, 0x5a, 0xba, 0x3d, 0x25, 0xf3, 0x7d, 0xff, 0xcc, 0xc0,
	0x40, 0xdd, 0x0d, 0x6e, 0xb5, 0x69, 0xbe, 0xbd, 0x8b, 0x0e, 0xab, 0xf4, 0x84, 0x9b, 0xcb, 0xb8,
	0xcb, 0x64, 0xb1, 0x86, 0xf2, 0x71, 0x1f, 0xc0, 0x7b, 0xa8, 0x5e, 0xd8, 0xac, 0xd9, 0x93, 0x90,
	0x42, 0xd5, 0xcb, 0xab, 0x1c, 0x08, 0x4d, 0xd2, 0x59, 0xe9, 0x43, 0x04, 0x1b, 0x98, 0xb7, 0xde,
	0xd8, 0x60, 0x56, 0xb1, 0x77, 0x36, 0xd0, 0x44, 0x4e, 0x55, 0xbd, 0x84, 0x63, 0x4b, 0xbb, 0xd3,
	0x67, 0x7e, 0xf1, 0x27, 0xa0, 0x1e, 0xcd, 0x41, 0x82, 0x8b, 0x4f, 0xf6, 0xa1, 0x77, 0x36, 0x6d,
	0x2b, 0xf5, 0xb1, 0xc4, 0x5b, 0x98, 0x3d, 0x7d, 0x19, 0x6b, 0x79, 0x78, 0x7d, 0xa6, 0x89, 0x14,
	0x6a, 0xa6, 0x4f, 0x00, 0xaf, 0xa1, 0x7a, 0xff, 0xd9, 0x76, 0xec, 0x69, 0x2a, 0x85, 0x2a, 0xf4,
	0xa1, 0xda, 0x77, 0x7d, 0x78, 0xfe, 0x4d, 0x2b, 0xa8, 0x90, 0x42, 0xcd, 0xf5, 0x09, 0xe0, 0x1d,
	0xc0, 0x1b, 0xfb, 0xcd, 0xc0, 0xda, 0xb9, 0x48, 0x65, 0xd2, 0x23, 0x82, 0x08, 0x45, 0xdb, 0x6f,
	0x99, 0xaa, 0x34, 0x33, 0xfd, 0xbb, 0x7c, 0xa9, 0x87, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47,
	0x83, 0xfe, 0xde, 0x3f, 0x01, 0x00, 0x00,
}
