// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Behavior defines the behavior
type Behavior int32

const (
	// Fail right away if not exist
	Behavior_FAIL_IF_NOT_READY Behavior = 0
	// Return until ready
	Behavior_RETURN_UNTIL_READY Behavior = 1
)

var Behavior_name = map[int32]string{
	0: "FAIL_IF_NOT_READY",
	1: "RETURN_UNTIL_READY",
}
var Behavior_value = map[string]int32{
	"FAIL_IF_NOT_READY":  0,
	"RETURN_UNTIL_READY": 1,
}

func (x Behavior) String() string {
	return proto.EnumName(Behavior_name, int32(x))
}
func (Behavior) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{0}
}

// Identity defines the identity in the channel
type Identity int32

const (
	Identity_MEMBER   Identity = 0
	Identity_ADMIN    Identity = 1
	Identity_OUTSIDER Identity = 2
)

var Identity_name = map[int32]string{
	0: "MEMBER",
	1: "ADMIN",
	2: "OUTSIDER",
}
var Identity_value = map[string]int32{
	"MEMBER":   0,
	"ADMIN":    1,
	"OUTSIDER": 2,
}

func (x Identity) String() string {
	return proto.EnumName(Identity_name, int32(x))
}
func (Identity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{1}
}

type PingRespond struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRespond) Reset()         { *m = PingRespond{} }
func (m *PingRespond) String() string { return proto.CompactTextString(m) }
func (*PingRespond) ProtoMessage()    {}
func (*PingRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{0}
}
func (m *PingRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRespond.Unmarshal(m, b)
}
func (m *PingRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRespond.Marshal(b, m, deterministic)
}
func (dst *PingRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRespond.Merge(dst, src)
}
func (m *PingRespond) XXX_Size() int {
	return xxx_messageInfo_PingRespond.Size(m)
}
func (m *PingRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRespond.DiscardUnknown(m)
}

var xxx_messageInfo_PingRespond proto.InternalMessageInfo

func (m *PingRespond) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// However, this is not contains sig now, but this is necessary
// if we want to verify the permission.
// TODO: add sig to identity.
type FetchBlockRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Behavior             Behavior `protobuf:"varint,3,opt,name=Behavior,proto3,enum=protos.Behavior" json:"Behavior,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchBlockRequest) Reset()         { *m = FetchBlockRequest{} }
func (m *FetchBlockRequest) String() string { return proto.CompactTextString(m) }
func (*FetchBlockRequest) ProtoMessage()    {}
func (*FetchBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{1}
}
func (m *FetchBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchBlockRequest.Unmarshal(m, b)
}
func (m *FetchBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchBlockRequest.Marshal(b, m, deterministic)
}
func (dst *FetchBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchBlockRequest.Merge(dst, src)
}
func (m *FetchBlockRequest) XXX_Size() int {
	return xxx_messageInfo_FetchBlockRequest.Size(m)
}
func (m *FetchBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchBlockRequest proto.InternalMessageInfo

func (m *FetchBlockRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *FetchBlockRequest) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *FetchBlockRequest) GetBehavior() Behavior {
	if m != nil {
		return m.Behavior
	}
	return Behavior_FAIL_IF_NOT_READY
}

// TODO: This should contain signature.
type ListChannelsRequest struct {
	// If system channel are included
	System               bool     `protobuf:"varint,1,opt,name=System,proto3" json:"System,omitempty"`
	PK                   []byte   `protobuf:"bytes,2,opt,name=PK,proto3" json:"PK,omitempty"`
	Algo                 int32    `protobuf:"varint,3,opt,name=Algo,proto3" json:"Algo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChannelsRequest) Reset()         { *m = ListChannelsRequest{} }
func (m *ListChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListChannelsRequest) ProtoMessage()    {}
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{2}
}
func (m *ListChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChannelsRequest.Unmarshal(m, b)
}
func (m *ListChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChannelsRequest.Marshal(b, m, deterministic)
}
func (dst *ListChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChannelsRequest.Merge(dst, src)
}
func (m *ListChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListChannelsRequest.Size(m)
}
func (m *ListChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListChannelsRequest proto.InternalMessageInfo

func (m *ListChannelsRequest) GetSystem() bool {
	if m != nil {
		return m.System
	}
	return false
}

func (m *ListChannelsRequest) GetPK() []byte {
	if m != nil {
		return m.PK
	}
	return nil
}

func (m *ListChannelsRequest) GetAlgo() int32 {
	if m != nil {
		return m.Algo
	}
	return 0
}

// ChannelInfos contains ChannelInfo
type ChannelInfos struct {
	Channels             []*ChannelInfo `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChannelInfos) Reset()         { *m = ChannelInfos{} }
func (m *ChannelInfos) String() string { return proto.CompactTextString(m) }
func (*ChannelInfos) ProtoMessage()    {}
func (*ChannelInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{3}
}
func (m *ChannelInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfos.Unmarshal(m, b)
}
func (m *ChannelInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfos.Marshal(b, m, deterministic)
}
func (dst *ChannelInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfos.Merge(dst, src)
}
func (m *ChannelInfos) XXX_Size() int {
	return xxx_messageInfo_ChannelInfos.Size(m)
}
func (m *ChannelInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfos.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfos proto.InternalMessageInfo

func (m *ChannelInfos) GetChannels() []*ChannelInfo {
	if m != nil {
		return m.Channels
	}
	return nil
}

// ChannelInfo includes some infomations of a channel
type ChannelInfo struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	BlockSize            uint64   `protobuf:"varint,2,opt,name=BlockSize,proto3" json:"BlockSize,omitempty"`
	Identity             Identity `protobuf:"varint,3,opt,name=Identity,proto3,enum=protos.Identity" json:"Identity,omitempty"`
	MaxGas               uint64   `protobuf:"varint,4,opt,name=MaxGas,proto3" json:"MaxGas,omitempty"`
	GasPrice             uint64   `protobuf:"varint,5,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	AssetTokenRatio      uint64   `protobuf:"varint,6,opt,name=AssetTokenRatio,proto3" json:"AssetTokenRatio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{4}
}
func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (dst *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(dst, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelInfo) GetBlockSize() uint64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *ChannelInfo) GetIdentity() Identity {
	if m != nil {
		return m.Identity
	}
	return Identity_MEMBER
}

func (m *ChannelInfo) GetMaxGas() uint64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

func (m *ChannelInfo) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *ChannelInfo) GetAssetTokenRatio() uint64 {
	if m != nil {
		return m.AssetTokenRatio
	}
	return 0
}

// CreateChannelRequest include a special tx which create a channel.
type CreateChannelRequest struct {
	Tx                   *Tx      `protobuf:"bytes,1,opt,name=Tx,proto3" json:"Tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChannelRequest) Reset()         { *m = CreateChannelRequest{} }
func (m *CreateChannelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChannelRequest) ProtoMessage()    {}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{5}
}
func (m *CreateChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelRequest.Unmarshal(m, b)
}
func (m *CreateChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelRequest.Marshal(b, m, deterministic)
}
func (dst *CreateChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelRequest.Merge(dst, src)
}
func (m *CreateChannelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChannelRequest.Size(m)
}
func (m *CreateChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelRequest proto.InternalMessageInfo

func (m *CreateChannelRequest) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

// CreateChannelTxPayload is the payload of create channel tx
type CreateChannelTxPayload struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChannelTxPayload) Reset()         { *m = CreateChannelTxPayload{} }
func (m *CreateChannelTxPayload) String() string { return proto.CompactTextString(m) }
func (*CreateChannelTxPayload) ProtoMessage()    {}
func (*CreateChannelTxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{6}
}
func (m *CreateChannelTxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelTxPayload.Unmarshal(m, b)
}
func (m *CreateChannelTxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelTxPayload.Marshal(b, m, deterministic)
}
func (dst *CreateChannelTxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelTxPayload.Merge(dst, src)
}
func (m *CreateChannelTxPayload) XXX_Size() int {
	return xxx_messageInfo_CreateChannelTxPayload.Size(m)
}
func (m *CreateChannelTxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelTxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelTxPayload proto.InternalMessageInfo

func (m *CreateChannelTxPayload) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type AddTxRequest struct {
	Tx                   *Tx      `protobuf:"bytes,1,opt,name=Tx,proto3" json:"Tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxRequest) Reset()         { *m = AddTxRequest{} }
func (m *AddTxRequest) String() string { return proto.CompactTextString(m) }
func (*AddTxRequest) ProtoMessage()    {}
func (*AddTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{7}
}
func (m *AddTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxRequest.Unmarshal(m, b)
}
func (m *AddTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxRequest.Marshal(b, m, deterministic)
}
func (dst *AddTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxRequest.Merge(dst, src)
}
func (m *AddTxRequest) XXX_Size() int {
	return xxx_messageInfo_AddTxRequest.Size(m)
}
func (m *AddTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxRequest proto.InternalMessageInfo

func (m *AddTxRequest) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

// TxStatus include nothing now.
type TxStatus struct {
	Err                  string   `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockIndex           int32    `protobuf:"varint,3,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	Output               []byte   `protobuf:"bytes,4,opt,name=Output,proto3" json:"Output,omitempty"`
	ContractAddress      string   `protobuf:"bytes,5,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxStatus) Reset()         { *m = TxStatus{} }
func (m *TxStatus) String() string { return proto.CompactTextString(m) }
func (*TxStatus) ProtoMessage()    {}
func (*TxStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{8}
}
func (m *TxStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxStatus.Unmarshal(m, b)
}
func (m *TxStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxStatus.Marshal(b, m, deterministic)
}
func (dst *TxStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxStatus.Merge(dst, src)
}
func (m *TxStatus) XXX_Size() int {
	return xxx_messageInfo_TxStatus.Size(m)
}
func (m *TxStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TxStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TxStatus proto.InternalMessageInfo

func (m *TxStatus) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *TxStatus) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TxStatus) GetBlockIndex() int32 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *TxStatus) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TxStatus) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type GetTxStatusRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=TxID,proto3" json:"TxID,omitempty"`
	Behavior             Behavior `protobuf:"varint,3,opt,name=Behavior,proto3,enum=protos.Behavior" json:"Behavior,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxStatusRequest) Reset()         { *m = GetTxStatusRequest{} }
func (m *GetTxStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTxStatusRequest) ProtoMessage()    {}
func (*GetTxStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{9}
}
func (m *GetTxStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxStatusRequest.Unmarshal(m, b)
}
func (m *GetTxStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetTxStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxStatusRequest.Merge(dst, src)
}
func (m *GetTxStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTxStatusRequest.Size(m)
}
func (m *GetTxStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxStatusRequest proto.InternalMessageInfo

func (m *GetTxStatusRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *GetTxStatusRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *GetTxStatusRequest) GetBehavior() Behavior {
	if m != nil {
		return m.Behavior
	}
	return Behavior_FAIL_IF_NOT_READY
}

type ListTxHistoryRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTxHistoryRequest) Reset()         { *m = ListTxHistoryRequest{} }
func (m *ListTxHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListTxHistoryRequest) ProtoMessage()    {}
func (*ListTxHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{10}
}
func (m *ListTxHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTxHistoryRequest.Unmarshal(m, b)
}
func (m *ListTxHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTxHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *ListTxHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTxHistoryRequest.Merge(dst, src)
}
func (m *ListTxHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListTxHistoryRequest.Size(m)
}
func (m *ListTxHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTxHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTxHistoryRequest proto.InternalMessageInfo

func (m *ListTxHistoryRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

// TxHistory includes all txs
type TxHistory struct {
	// repeated string Txs = 1;
	Txs                  map[string]*StringList `protobuf:"bytes,1,rep,name=Txs,proto3" json:"Txs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TxHistory) Reset()         { *m = TxHistory{} }
func (m *TxHistory) String() string { return proto.CompactTextString(m) }
func (*TxHistory) ProtoMessage()    {}
func (*TxHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{11}
}
func (m *TxHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxHistory.Unmarshal(m, b)
}
func (m *TxHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxHistory.Marshal(b, m, deterministic)
}
func (dst *TxHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxHistory.Merge(dst, src)
}
func (m *TxHistory) XXX_Size() int {
	return xxx_messageInfo_TxHistory.Size(m)
}
func (m *TxHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_TxHistory.DiscardUnknown(m)
}

var xxx_messageInfo_TxHistory proto.InternalMessageInfo

func (m *TxHistory) GetTxs() map[string]*StringList {
	if m != nil {
		return m.Txs
	}
	return nil
}

type GetAccountInfoRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountInfoRequest) Reset()         { *m = GetAccountInfoRequest{} }
func (m *GetAccountInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoRequest) ProtoMessage()    {}
func (*GetAccountInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{12}
}
func (m *GetAccountInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoRequest.Unmarshal(m, b)
}
func (m *GetAccountInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoRequest.Merge(dst, src)
}
func (m *GetAccountInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoRequest.Size(m)
}
func (m *GetAccountInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoRequest proto.InternalMessageInfo

func (m *GetAccountInfoRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type AccountInfo struct {
	Balance              uint64   `protobuf:"varint,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{13}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (dst *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(dst, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetTokenInfoRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	ChannelID            []byte   `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoRequest) Reset()         { *m = GetTokenInfoRequest{} }
func (m *GetTokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoRequest) ProtoMessage()    {}
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{14}
}
func (m *GetTokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoRequest.Unmarshal(m, b)
}
func (m *GetTokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoRequest.Merge(dst, src)
}
func (m *GetTokenInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoRequest.Size(m)
}
func (m *GetTokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoRequest proto.InternalMessageInfo

func (m *GetTokenInfoRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetTokenInfoRequest) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

type TokenInfo struct {
	Balance              uint64   `protobuf:"varint,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{15}
}
func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (dst *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(dst, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetBlockRequest struct {
	ChannelID            []byte   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	BlockIndex           uint64   `protobuf:"varint,2,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4f6396399504a7f7, []int{16}
}
func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(dst, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

func (m *GetBlockRequest) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*PingRespond)(nil), "protos.PingRespond")
	proto.RegisterType((*FetchBlockRequest)(nil), "protos.FetchBlockRequest")
	proto.RegisterType((*ListChannelsRequest)(nil), "protos.ListChannelsRequest")
	proto.RegisterType((*ChannelInfos)(nil), "protos.ChannelInfos")
	proto.RegisterType((*ChannelInfo)(nil), "protos.ChannelInfo")
	proto.RegisterType((*CreateChannelRequest)(nil), "protos.CreateChannelRequest")
	proto.RegisterType((*CreateChannelTxPayload)(nil), "protos.CreateChannelTxPayload")
	proto.RegisterType((*AddTxRequest)(nil), "protos.AddTxRequest")
	proto.RegisterType((*TxStatus)(nil), "protos.TxStatus")
	proto.RegisterType((*GetTxStatusRequest)(nil), "protos.GetTxStatusRequest")
	proto.RegisterType((*ListTxHistoryRequest)(nil), "protos.ListTxHistoryRequest")
	proto.RegisterType((*TxHistory)(nil), "protos.TxHistory")
	proto.RegisterMapType((map[string]*StringList)(nil), "protos.TxHistory.TxsEntry")
	proto.RegisterType((*GetAccountInfoRequest)(nil), "protos.GetAccountInfoRequest")
	proto.RegisterType((*AccountInfo)(nil), "protos.AccountInfo")
	proto.RegisterType((*GetTokenInfoRequest)(nil), "protos.GetTokenInfoRequest")
	proto.RegisterType((*TokenInfo)(nil), "protos.TokenInfo")
	proto.RegisterType((*GetBlockRequest)(nil), "protos.GetBlockRequest")
	proto.RegisterEnum("protos.Behavior", Behavior_name, Behavior_value)
	proto.RegisterEnum("protos.Identity", Identity_name, Identity_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrdererClient is the client API for Orderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdererClient interface {
	FetchBlock(ctx context.Context, in *FetchBlockRequest, opts ...grpc.CallOption) (*Block, error)
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ChannelInfos, error)
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelInfo, error)
	AddTx(ctx context.Context, in *AddTxRequest, opts ...grpc.CallOption) (*TxStatus, error)
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*AccountInfo, error)
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingRespond, error)
}

type ordererClient struct {
	cc *grpc.ClientConn
}

func NewOrdererClient(cc *grpc.ClientConn) OrdererClient {
	return &ordererClient{cc}
}

func (c *ordererClient) FetchBlock(ctx context.Context, in *FetchBlockRequest, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/protos.Orderer/FetchBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ChannelInfos, error) {
	out := new(ChannelInfos)
	err := c.cc.Invoke(ctx, "/protos.Orderer/ListChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelInfo, error) {
	out := new(ChannelInfo)
	err := c.cc.Invoke(ctx, "/protos.Orderer/CreateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) AddTx(ctx context.Context, in *AddTxRequest, opts ...grpc.CallOption) (*TxStatus, error) {
	out := new(TxStatus)
	err := c.cc.Invoke(ctx, "/protos.Orderer/AddTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*AccountInfo, error) {
	out := new(AccountInfo)
	err := c.cc.Invoke(ctx, "/protos.Orderer/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingRespond, error) {
	out := new(PingRespond)
	err := c.cc.Invoke(ctx, "/protos.Orderer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdererServer is the server API for Orderer service.
type OrdererServer interface {
	FetchBlock(context.Context, *FetchBlockRequest) (*Block, error)
	ListChannels(context.Context, *ListChannelsRequest) (*ChannelInfos, error)
	CreateChannel(context.Context, *CreateChannelRequest) (*ChannelInfo, error)
	AddTx(context.Context, *AddTxRequest) (*TxStatus, error)
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*AccountInfo, error)
	Ping(context.Context, *empty.Empty) (*PingRespond, error)
}

func RegisterOrdererServer(s *grpc.Server, srv OrdererServer) {
	s.RegisterService(&_Orderer_serviceDesc, srv)
}

func _Orderer_FetchBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).FetchBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/FetchBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).FetchBlock(ctx, req.(*FetchBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/ListChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/CreateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_AddTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).AddTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/AddTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).AddTx(ctx, req.(*AddTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Orderer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Orderer",
	HandlerType: (*OrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchBlock",
			Handler:    _Orderer_FetchBlock_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _Orderer_ListChannels_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _Orderer_CreateChannel_Handler,
		},
		{
			MethodName: "AddTx",
			Handler:    _Orderer_AddTx_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _Orderer_GetAccountInfo_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Orderer_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerClient interface {
	GetTxStatus(ctx context.Context, in *GetTxStatusRequest, opts ...grpc.CallOption) (*TxStatus, error)
	ListTxHistory(ctx context.Context, in *ListTxHistoryRequest, opts ...grpc.CallOption) (*TxHistory, error)
	GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*TokenInfo, error)
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingRespond, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) GetTxStatus(ctx context.Context, in *GetTxStatusRequest, opts ...grpc.CallOption) (*TxStatus, error) {
	out := new(TxStatus)
	err := c.cc.Invoke(ctx, "/protos.Peer/GetTxStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) ListTxHistory(ctx context.Context, in *ListTxHistoryRequest, opts ...grpc.CallOption) (*TxHistory, error) {
	out := new(TxHistory)
	err := c.cc.Invoke(ctx, "/protos.Peer/ListTxHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*TokenInfo, error) {
	out := new(TokenInfo)
	err := c.cc.Invoke(ctx, "/protos.Peer/GetTokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingRespond, error) {
	out := new(PingRespond)
	err := c.cc.Invoke(ctx, "/protos.Peer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/protos.Peer/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
type PeerServer interface {
	GetTxStatus(context.Context, *GetTxStatusRequest) (*TxStatus, error)
	ListTxHistory(context.Context, *ListTxHistoryRequest) (*TxHistory, error)
	GetTokenInfo(context.Context, *GetTokenInfoRequest) (*TokenInfo, error)
	Ping(context.Context, *empty.Empty) (*PingRespond, error)
	GetBlock(context.Context, *GetBlockRequest) (*Block, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_GetTxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).GetTxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/GetTxStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).GetTxStatus(ctx, req.(*GetTxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_ListTxHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).ListTxHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/ListTxHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).ListTxHistory(ctx, req.(*ListTxHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/GetTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).GetTokenInfo(ctx, req.(*GetTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTxStatus",
			Handler:    _Peer_GetTxStatus_Handler,
		},
		{
			MethodName: "ListTxHistory",
			Handler:    _Peer_ListTxHistory_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _Peer_GetTokenInfo_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Peer_Ping_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _Peer_GetBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_4f6396399504a7f7) }

var fileDescriptor_service_4f6396399504a7f7 = []byte{
	// 966 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0x22, 0x47,
	0x13, 0x66, 0x38, 0x19, 0x0a, 0xec, 0xc5, 0x65, 0x2f, 0x3f, 0xff, 0xac, 0x13, 0xa1, 0x96, 0xa2,
	0x45, 0xd6, 0x0a, 0x67, 0xc9, 0x41, 0x9b, 0x48, 0x51, 0x02, 0x06, 0x13, 0xb2, 0xe6, 0x90, 0x66,
	0x1c, 0x29, 0x57, 0xd6, 0x18, 0x7a, 0xf1, 0xc8, 0x30, 0xe3, 0x4c, 0x37, 0xce, 0x90, 0xab, 0xdc,
	0xe4, 0x3d, 0xf2, 0x18, 0x79, 0x91, 0xbc, 0x4f, 0x34, 0x3d, 0xd3, 0xcc, 0xc0, 0x22, 0xaf, 0x93,
	0x2b, 0xa6, 0xaa, 0xbf, 0xae, 0xaa, 0xfe, 0xba, 0xea, 0x6b, 0x60, 0x9f, 0x33, 0xf7, 0xc1, 0x9a,
	0xb0, 0xfa, 0xbd, 0xeb, 0x08, 0x07, 0xb3, 0xf2, 0x87, 0xeb, 0x2f, 0x66, 0x8e, 0x33, 0x9b, 0xb3,
	0x33, 0x69, 0xde, 0x2c, 0xdf, 0x9d, 0xb1, 0xc5, 0xbd, 0x58, 0x05, 0x20, 0xbd, 0x38, 0x71, 0x16,
	0x0b, 0xc7, 0x0e, 0xad, 0x9c, 0xf0, 0xc2, 0xaf, 0xc2, 0xcd, 0xdc, 0x99, 0xdc, 0x05, 0x06, 0x79,
	0x09, 0x85, 0x91, 0x65, 0xcf, 0x28, 0xe3, 0xf7, 0x8e, 0x3d, 0xc5, 0x0a, 0xec, 0xfd, 0xc4, 0x5c,
	0x6e, 0x39, 0x76, 0x45, 0xab, 0x6a, 0xb5, 0x3c, 0x55, 0x26, 0xf9, 0x15, 0x0e, 0x2f, 0x98, 0x98,
	0xdc, 0xb6, 0xfc, 0xcd, 0x94, 0xfd, 0xb2, 0x64, 0x5c, 0xe0, 0x09, 0xe4, 0xcf, 0x6f, 0x4d, 0xdb,
	0x66, 0xf3, 0x5e, 0x3b, 0xdc, 0x10, 0x39, 0xb0, 0x0c, 0xd9, 0xc1, 0x72, 0x71, 0xc3, 0xdc, 0x4a,
	0xb2, 0xaa, 0xd5, 0xd2, 0x34, 0xb4, 0xf0, 0x15, 0xe4, 0x5a, 0xec, 0xd6, 0x7c, 0xb0, 0x1c, 0xb7,
	0x92, 0xaa, 0x6a, 0xb5, 0x83, 0x46, 0x29, 0xa8, 0x86, 0xd7, 0x95, 0x9f, 0xae, 0x11, 0xe4, 0x47,
	0x38, 0xba, 0xb4, 0xb8, 0x08, 0xc3, 0x72, 0x95, 0xba, 0x0c, 0xd9, 0xf1, 0x8a, 0x0b, 0xb6, 0x90,
	0x79, 0x73, 0x34, 0xb4, 0xf0, 0x00, 0x92, 0xa3, 0xb7, 0x32, 0x61, 0x91, 0x26, 0x47, 0x6f, 0x11,
	0x21, 0xdd, 0x9c, 0xcf, 0x1c, 0x99, 0x28, 0x43, 0xe5, 0x37, 0xf9, 0x16, 0x8a, 0xaa, 0x4a, 0xfb,
	0x9d, 0xc3, 0xf1, 0x0c, 0x72, 0x2a, 0x7c, 0x45, 0xab, 0xa6, 0x6a, 0x85, 0xc6, 0x91, 0x2a, 0x28,
	0x86, 0xa3, 0x6b, 0x10, 0xf9, 0x5b, 0x83, 0x42, 0x6c, 0xe5, 0x03, 0x3c, 0x9c, 0x40, 0x5e, 0xb2,
	0x36, 0xb6, 0x7e, 0x63, 0x21, 0x15, 0x91, 0xc3, 0x67, 0xa3, 0x37, 0x65, 0xb6, 0xb0, 0xc4, 0x6a,
	0x9b, 0x0d, 0xe5, 0xa7, 0x6b, 0x84, 0x7f, 0xec, 0xbe, 0xe9, 0x75, 0x4d, 0x5e, 0x49, 0x07, 0x9c,
	0x06, 0x16, 0xea, 0x90, 0xeb, 0x9a, 0x7c, 0xe4, 0x5a, 0x13, 0x56, 0xc9, 0xc8, 0x95, 0xb5, 0x8d,
	0x35, 0x78, 0xd6, 0xe4, 0x9c, 0x09, 0xc3, 0xb9, 0x63, 0x36, 0x35, 0x85, 0xe5, 0x54, 0xb2, 0x12,
	0xb2, 0xed, 0x26, 0x0d, 0x38, 0x3e, 0x77, 0x99, 0x29, 0x58, 0x58, 0xbc, 0x22, 0x5b, 0x87, 0xa4,
	0xe1, 0xc9, 0x83, 0x15, 0x1a, 0xa0, 0xaa, 0x33, 0x3c, 0x9a, 0x34, 0x3c, 0xf2, 0x25, 0x94, 0x37,
	0xf6, 0x18, 0xde, 0xc8, 0x5c, 0xcd, 0x1d, 0x73, 0xfa, 0x38, 0x2b, 0xe4, 0x14, 0x8a, 0xcd, 0xe9,
	0xd4, 0xf0, 0x9e, 0x92, 0xe3, 0x4f, 0x0d, 0x72, 0x86, 0x37, 0x16, 0xa6, 0x58, 0x72, 0x2c, 0x41,
	0xaa, 0xe3, 0xba, 0x61, 0x40, 0xff, 0x13, 0xab, 0x50, 0x90, 0x7c, 0x6e, 0x74, 0x5b, 0xdc, 0x85,
	0x1f, 0x03, 0x48, 0xb3, 0x67, 0x4f, 0x99, 0x17, 0xf6, 0x42, 0xcc, 0xe3, 0xd3, 0x3a, 0x5c, 0x8a,
	0xfb, 0xa5, 0x90, 0xb4, 0x16, 0x69, 0x68, 0xf9, 0xd4, 0x9d, 0x3b, 0xb6, 0x70, 0xcd, 0x89, 0x68,
	0x4e, 0xa7, 0x2e, 0xe3, 0x5c, 0xb2, 0x9b, 0xa7, 0xdb, 0x6e, 0x22, 0x00, 0xbb, 0x4c, 0xa8, 0x22,
	0x9f, 0x36, 0x20, 0x08, 0x69, 0xc3, 0xeb, 0xb5, 0x65, 0xc1, 0x79, 0x2a, 0xbf, 0xff, 0xe5, 0x70,
	0x7c, 0x0a, 0xc7, 0xfe, 0x70, 0x18, 0xde, 0xf7, 0x16, 0x17, 0x8e, 0xbb, 0x52, 0x79, 0x2b, 0xb0,
	0xa7, 0xea, 0xd5, 0xe4, 0x81, 0x94, 0x49, 0xfe, 0xd0, 0x20, 0xbf, 0x86, 0xe3, 0x2b, 0x48, 0x19,
	0x9e, 0x6a, 0x7a, 0x3d, 0x62, 0x3d, 0x5c, 0xaf, 0x1b, 0x1e, 0xef, 0xd8, 0xc2, 0x5d, 0x51, 0x1f,
	0xa6, 0xff, 0xe0, 0xdf, 0x42, 0xe0, 0xf0, 0x6f, 0xe1, 0x8e, 0xad, 0xd4, 0x2d, 0xdc, 0xb1, 0x15,
	0xd6, 0x20, 0xf3, 0x60, 0xce, 0x97, 0x41, 0x8b, 0x17, 0x1a, 0xa8, 0xa2, 0x8d, 0x85, 0x6b, 0xd9,
	0x33, 0xbf, 0x4c, 0x1a, 0x00, 0xbe, 0x4e, 0xbe, 0xd1, 0xc8, 0x6b, 0x78, 0xde, 0x65, 0xa2, 0x39,
	0x99, 0x38, 0x4b, 0x5b, 0xc8, 0xf1, 0xfa, 0x60, 0xe9, 0x2f, 0xa1, 0x10, 0xc3, 0xfb, 0xc0, 0x96,
	0x39, 0x37, 0xed, 0x09, 0x93, 0xc0, 0x34, 0x55, 0x26, 0xe9, 0xc3, 0x51, 0x37, 0xec, 0xeb, 0x27,
	0x45, 0xde, 0xbc, 0xa6, 0x40, 0x3b, 0x62, 0x9d, 0xfa, 0x09, 0xe4, 0xd7, 0xb1, 0x1e, 0xc9, 0x3a,
	0x84, 0x67, 0x5d, 0x26, 0x1e, 0xd7, 0xc7, 0x78, 0xdc, 0xad, 0xa6, 0x0c, 0xba, 0x36, 0xe6, 0x39,
	0xfd, 0x2a, 0x6a, 0x05, 0x7c, 0x0e, 0x87, 0x17, 0xcd, 0xde, 0xe5, 0x75, 0xef, 0xe2, 0x7a, 0x30,
	0x34, 0xae, 0x69, 0xa7, 0xd9, 0xfe, 0xb9, 0x94, 0xc0, 0x32, 0x20, 0xed, 0x18, 0x57, 0x74, 0x70,
	0x7d, 0x35, 0x30, 0x7a, 0x97, 0xa1, 0x5f, 0x3b, 0x3d, 0x8b, 0x44, 0x05, 0x01, 0xb2, 0xfd, 0x4e,
	0xbf, 0xd5, 0xa1, 0xa5, 0x04, 0xe6, 0x21, 0xd3, 0x6c, 0xf7, 0x7b, 0x83, 0x92, 0x86, 0x45, 0xc8,
	0x0d, 0xaf, 0x8c, 0x71, 0xaf, 0xdd, 0xa1, 0xa5, 0x64, 0xe3, 0xf7, 0x14, 0xec, 0x0d, 0xdd, 0x29,
	0x73, 0x99, 0x8b, 0x6f, 0x00, 0x22, 0xa9, 0xc7, 0xff, 0xab, 0x7b, 0x7c, 0x4f, 0xfe, 0xf5, 0xfd,
	0x75, 0x67, 0xfa, 0x5e, 0x92, 0xc0, 0x73, 0x28, 0xc6, 0xb5, 0x1a, 0x5f, 0x28, 0xc0, 0x0e, 0x05,
	0xd7, 0x8f, 0x77, 0x68, 0x2c, 0x27, 0x09, 0x6c, 0xc3, 0xfe, 0x86, 0xa0, 0xe0, 0xc9, 0x1a, 0xb8,
	0x43, 0x9b, 0xf4, 0x5d, 0x52, 0x4d, 0x12, 0xf8, 0x1a, 0x32, 0x52, 0x5e, 0x70, 0x9d, 0x26, 0xae,
	0x36, 0x7a, 0x29, 0xea, 0xf5, 0x60, 0x62, 0x49, 0x02, 0x2f, 0xe0, 0x60, 0xb3, 0x25, 0xf1, 0x23,
	0x85, 0xda, 0xd9, 0xaa, 0x51, 0xea, 0xd8, 0x1a, 0x49, 0xe0, 0x17, 0x90, 0xf6, 0xdf, 0x54, 0x2c,
	0xd7, 0x83, 0xe7, 0xb9, 0xae, 0x9e, 0xe7, 0x7a, 0xc7, 0x7f, 0x9e, 0xa3, 0x6d, 0xb1, 0x97, 0x97,
	0x24, 0x1a, 0x7f, 0x25, 0x21, 0x3d, 0x62, 0xcc, 0xc5, 0x6f, 0xa0, 0x10, 0x93, 0x12, 0xd4, 0x63,
	0x45, 0x6c, 0xe9, 0xcb, 0xce, 0x63, 0xb4, 0x60, 0x7f, 0x43, 0x13, 0x22, 0xfe, 0x76, 0x49, 0x85,
	0x7e, 0xf8, 0xde, 0xd4, 0x93, 0x04, 0x7e, 0x07, 0xc5, 0xf8, 0x04, 0x45, 0x17, 0xb9, 0x63, 0xae,
	0x62, 0x11, 0xd4, 0xca, 0x7f, 0x26, 0x01, 0x3f, 0x87, 0x9c, 0x1a, 0x22, 0xfc, 0x5f, 0x2c, 0xe9,
	0xa3, 0x7d, 0x77, 0x13, 0xfc, 0x1f, 0xfa, 0xec, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x33,
	0x3e, 0xdd, 0x27, 0x09, 0x00, 0x00,
}
