// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tx.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Tx is the transaction, which structure is not decided yet
type Tx struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 *TxData  `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_tx_d4de439b9d930a98, []int{0}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Tx) GetData() *TxData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Tx) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// txData is the data of Tx
type TxData struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Recipient            []byte   `protobuf:"bytes,3,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Sig                  *TxSig   `protobuf:"bytes,6,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxData) Reset()         { *m = TxData{} }
func (m *TxData) String() string { return proto.CompactTextString(m) }
func (*TxData) ProtoMessage()    {}
func (*TxData) Descriptor() ([]byte, []int) {
	return fileDescriptor_tx_d4de439b9d930a98, []int{1}
}
func (m *TxData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxData.Unmarshal(m, b)
}
func (m *TxData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxData.Marshal(b, m, deterministic)
}
func (dst *TxData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxData.Merge(dst, src)
}
func (m *TxData) XXX_Size() int {
	return xxx_messageInfo_TxData.Size(m)
}
func (m *TxData) XXX_DiscardUnknown() {
	xxx_messageInfo_TxData.DiscardUnknown(m)
}

var xxx_messageInfo_TxData proto.InternalMessageInfo

func (m *TxData) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *TxData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TxData) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *TxData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TxData) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TxData) GetSig() *TxSig {
	if m != nil {
		return m.Sig
	}
	return nil
}

// txSig is the sig of tx
// However, it has a gap with the struct of txSig,
// because there is no big int in the protobuf
type TxSig struct {
	PK                   []byte   `protobuf:"bytes,1,opt,name=PK,proto3" json:"PK,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxSig) Reset()         { *m = TxSig{} }
func (m *TxSig) String() string { return proto.CompactTextString(m) }
func (*TxSig) ProtoMessage()    {}
func (*TxSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_tx_d4de439b9d930a98, []int{2}
}
func (m *TxSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxSig.Unmarshal(m, b)
}
func (m *TxSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxSig.Marshal(b, m, deterministic)
}
func (dst *TxSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxSig.Merge(dst, src)
}
func (m *TxSig) XXX_Size() int {
	return xxx_messageInfo_TxSig.Size(m)
}
func (m *TxSig) XXX_DiscardUnknown() {
	xxx_messageInfo_TxSig.DiscardUnknown(m)
}

var xxx_messageInfo_TxSig proto.InternalMessageInfo

func (m *TxSig) GetPK() []byte {
	if m != nil {
		return m.PK
	}
	return nil
}

func (m *TxSig) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*Tx)(nil), "protos.Tx")
	proto.RegisterType((*TxData)(nil), "protos.txData")
	proto.RegisterType((*TxSig)(nil), "protos.txSig")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor_tx_d4de439b9d930a98) }

var fileDescriptor_tx_d4de439b9d930a98 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x49, 0xf6, 0x8f, 0x76, 0xac, 0x45, 0x06, 0x0f, 0x39, 0x08, 0x2e, 0x7b, 0x8a, 0x97,
	0x1e, 0xf4, 0x11, 0xdc, 0x4b, 0xa9, 0xc8, 0x32, 0x2d, 0xde, 0x63, 0x0d, 0x35, 0x50, 0x93, 0xd2,
	0xcd, 0x61, 0x7d, 0x2a, 0x5f, 0x51, 0x32, 0xa1, 0xdd, 0x53, 0xe6, 0xfb, 0x7e, 0xf9, 0x26, 0x99,
	0x81, 0xeb, 0x38, 0x2e, 0x8f, 0xa7, 0x10, 0x03, 0xd6, 0x7c, 0x0c, 0xed, 0x1b, 0xc8, 0xed, 0x88,
	0x0b, 0x90, 0xab, 0x4e, 0x89, 0x46, 0xe8, 0x19, 0xc9, 0x55, 0x87, 0x2d, 0x94, 0x9d, 0x89, 0x46,
	0xc9, 0x46, 0xe8, 0x9b, 0xe7, 0x45, 0xce, 0x0c, 0xcb, 0x38, 0x26, 0x97, 0x98, 0x21, 0x42, 0xb9,
	0x75, 0x3f, 0x56, 0x15, 0x8d, 0xd0, 0x05, 0x71, 0xdd, 0xfe, 0x09, 0xa8, 0xf3, 0x25, 0x7c, 0x80,
	0xd9, 0xeb, 0xb7, 0xf1, 0xde, 0x1e, 0x2e, 0x9d, 0x27, 0x03, 0xef, 0xa1, 0x7a, 0x0f, 0x7e, 0x67,
	0xf9, 0x85, 0x92, 0xb2, 0x48, 0x19, 0xb2, 0x3b, 0x77, 0x74, 0xd6, 0x47, 0xee, 0x3b, 0xa7, 0xc9,
	0x40, 0x05, 0x57, 0xbd, 0xf9, 0x3d, 0x04, 0xf3, 0xa5, 0x4a, 0x66, 0x67, 0x99, 0xc8, 0x87, 0x3d,
	0x0d, 0x2e, 0x78, 0x55, 0x35, 0x42, 0x57, 0x74, 0x96, 0xf8, 0x08, 0xc5, 0xc6, 0xed, 0x55, 0xcd,
	0x73, 0xdc, 0x4e, 0x73, 0x6c, 0xdc, 0x9e, 0x12, 0x69, 0x9f, 0xa0, 0x62, 0x95, 0x56, 0xd0, 0xaf,
	0xf9, 0xa3, 0x73, 0x92, 0xfd, 0x1a, 0xef, 0x72, 0x52, 0xb2, 0x91, 0xca, 0xcf, 0xbc, 0xb2, 0x97,
	0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xcd, 0xdb, 0xb9, 0x45, 0x01, 0x00, 0x00,
}
